version: '3.8'

services:
  php:
    image: pick-up-status-display_php:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: HeberosiaStore
      MYSQL_USER: janjanjan
      MYSQL_PASSWORD: janjan123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3333:3306"

volumes:
  db_data:
